run:
  timeout: 5m
  # version: "2" is implied by default for newer versions, but making it explicit helps with strict parsers
  # and avoids "unsupported version of the configuration: """ errors in some environments.


linters:
  enable:
    - forbidigo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - errcheck
    - gosec
    - misspell
    - unparam
    - prealloc
  disable:
    - typecheck

linters-settings:
  forbidigo:
    forbid:
      - p: ^fmt\.Sprintf$
        msg: "Use strings.ReplaceAll for simple substitutions or text/template for complex ones to avoid % injection attacks."
