run:
  timeout: 5m

# Explicitly set configuration version to avoid "unsupported version" errors
version: "2"



linters:
  enable:
    - forbidigo
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - errcheck
    - gosec
    - misspell
    - unparam
    - prealloc
  disable:


linters-settings:
  forbidigo:
    forbid:
      - p: ^fmt\.Sprintf$
        msg: "Use strings.ReplaceAll for simple substitutions or text/template for complex ones to avoid % injection attacks."
